import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import Header from "../components/Header";
import { cookies as nextCookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read cookie on the server to determine initial color mode
  const cookieStore = await nextCookies();
  const cookie = cookieStore.get?.("chakra-ui-color-mode");
  const initialColorMode = cookie?.value; // 'light' | 'dark' | undefined

  // Only include the beforeInteractive fallback if there's no cookie
  // Fallback can be disabled via NEXT_PUBLIC_DISABLE_FALLBACK=true
  const disableFallback = process.env.NEXT_PUBLIC_DISABLE_FALLBACK === "true";
  const setInitialColorMode = `(function() {
    try {
      // If cookie is not set, fall back to prefers-color-scheme
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const prefersDark = mql.matches;
      const mode = prefersDark ? 'dark' : 'light';
      document.documentElement.setAttribute('data-theme', mode);
      document.documentElement.style.colorScheme = mode;
    } catch (e) {
      // ignore
    }
  })();`;

  return (
    <html
      suppressHydrationWarning
      lang="en"
      {...(initialColorMode
        ? {
            // If cookie exists, render server HTML with correct attributes
            "data-theme": initialColorMode,
            style: { colorScheme: initialColorMode },
          }
        : {})}
    >
      <head>
        {/* If there's no server cookie, run a lightweight script before hydration unless disabled */}
        {!initialColorMode && !disableFallback ? (
          <Script id="chakra-init" strategy="beforeInteractive">
            {setInitialColorMode}
          </Script>
        ) : null}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
