import type { Metadata } from "next";
// Removed next/script dark-mode init — system no longer uses dark mode
import { cn } from "@/lib/cn";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import Header from "../components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Dark-mode initialization removed

  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body suppressHydrationWarning className={cn(geistSans.variable, geistMono.variable, "flex flex-col antialiased min-h-screen overflow-auto")}>
        <Providers>
          <Header />
          <main className="grow flex flex-col">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
