import type { Metadata } from "next";
import Script from "next/script";
import { cn } from "@/lib/cn";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import Header from "../components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // We'll set theme (dark class) on the client before hydration using localStorage
  // Fallback behavior can be disabled with NEXT_PUBLIC_DISABLE_FALLBACK=true
  const disableFallback = process.env.NEXT_PUBLIC_DISABLE_FALLBACK === "true";
  const setInitialColorMode = `(function() {
    try {
      var stored = null;
      try { stored = localStorage.getItem('theme'); } catch(e){}
      if (stored === 'dark') {
        document.documentElement.classList.add('dark');
      } else if (stored === 'light') {
        document.documentElement.classList.remove('dark');
      } else {
        var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
        if (prefersDark) document.documentElement.classList.add('dark');
      }
    } catch (e) {}
  })();`;

  return (
    <html suppressHydrationWarning lang="en">
      <head>
        {/* If there's no server cookie, run a lightweight script before hydration unless disabled */}
        {!disableFallback ? (
          <Script id="theme-init" strategy="beforeInteractive">
            {setInitialColorMode}
          </Script>
        ) : null}
      </head>
      <body suppressHydrationWarning className={cn(geistSans.variable, geistMono.variable, "flex flex-col antialiased min-h-screen overflow-auto")}>
        <Providers>
          <Header />
          <main className="grow flex flex-col">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
